apiVersion: v1
kind: Service
metadata:
  name: order-java-fault
  namespace: kube-copilot-lab
spec:
  selector:
    app: order-java-fault
  ports:
    - name: http
      port: 8082
      targetPort: 8082
