apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-fault
  namespace: kube-copilot-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-fault
  template:
    metadata:
      labels:
        app: payment-fault
    spec:
      initContainers:
        - name: wait-for-otel-collector
          image: kube-cluster-copilot/payment-fault:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until nc -z -w 2 otel-collector.observability.svc.cluster.local 4317; do
                echo "waiting for signoz otel collector"
                sleep 2
              done
      containers:
        - name: payment-fault
          image: kube-cluster-copilot/payment-fault:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: payment-fault-config
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
