apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: otel-collector
  ports:
    - name: otlp
      port: 4317
      targetPort: otlp
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
